02 - vue calculator
js-tasks-ru/vue-20210810_dinmukhammadiieva pull request #2
Opened 2021-08-08 09:29 UTC by naziradenushka

2021-08-08 09:30 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-08-08 09:33 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-08-08 09:59 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2021-08-08 10:11 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-08-08 10:57 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2021-08-08 11:09 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-08-08 14:15 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-08-08 17:03 UTC, ShGKme requested changes
Решение задачи `CounterButtonComponent` предлагается обновить, оставив не более 2-х свойств для работы со значением счётчика. Остальные задачи приняты

2021-08-08 17:03 UTC, ShGKme commented on 02-components/01-CounterButtonComponent/CounterButton.js
> +  },
Для работы счётчика с одним числом сейчас используется 3 разных свойства - входной параметр, локальное свойство и вычисляемое свойство, из-за чего решение получается довольно сложным.

Минимально для решения задачи достаточно всего одного свойства - входного параметра. По условию компонент только отображается текущее значение входного параметра и отправляет с событием новое значение после клика. Для этого ничего, кроме входного параметра - не требуется.

Добавлять локальное состояние можно, если требуется поддерживать работу компонента и без установки `v-model` родителем. Но и для этого достаточно добавить только локальное состояние и отслеживание входного параметра для синхронизации значения.

2021-08-08 17:03 UTC, ShGKme commented on 01-basics/02-VueCalculator/script.js
> +    },
Если использовать модификатор [`v-model.number`](https://v3.vuejs.org/guide/forms.html#number), то введённое значение можно получать в виде числа сразу в состоянии компонента, а не переводить в каждом вычислении.

2021-08-08 17:03 UTC, ShGKme commented on 01-basics/02-VueCalculator/script.js
> +    },
Хотя вычисляемые свойства и описываются с геттером, это именно свойства. Значение свойства вычисляется Vue через описанную функцию, но свойство - остаётся просто свойством со своим значением. По этой причине их обычно называют, как свойства, а не как функции с глаголом.

2021-08-08 17:03 UTC, ShGKme commented on 01-basics/03-MarkedList/script.js
> +    },
Метод массива [`map`](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/map) значительно упрощает такие функции

2021-08-08 17:03 UTC, ShGKme commented on 01-basics/04-MeetupTitle/index.html
> +        <label><input v-model="meetupId" name="meetupId" type="radio" value="5" /> 5</label>
Можно использовать `v-for="i in 5"`, чтобы избавиться от дублирования кода.

2021-08-08 17:04 UTC, ShGKme commented
Тесты не проходят из-за ошибки в обновлении задачника новой группы. Задачник обновил, требуется синхронизировать:
```bash
git pull upstream master
git push origin master
```

2021-08-10 16:16 UTC, naziradenushka commented
здравствуйте, спасибо большое, прочту, учту и сделаю)

  
>Воскресенье, 8 августа 2021, 22:04 +05:00 от Grigorii K. Shartsev ***@***.***>:
> 
> 
>Тесты не проходят из-за ошибки в обновлении задачника новой группы. Задачник обновил, требуется синхронизировать:
>git pull upstream master
>
>git push origin master
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android . 
 
 
С уважением,
Назира Динмухаммадиева
***@***.***
 

2021-08-13 15:48 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-08-13 16:32 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-08-13 19:11 UTC, ShGKme approved these changes
Все задачи приняты 👍

2021-08-13 19:11 UTC, merged